/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IStableLPToken,
  IStableLPTokenInterface,
} from "../IStableLPToken";

const _abi = [
  {
    inputs: [],
    name: "swap",
    outputs: [
      {
        internalType: "contract ISwap",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IStableLPToken__factory {
  static readonly abi = _abi;
  static createInterface(): IStableLPTokenInterface {
    return new utils.Interface(_abi) as IStableLPTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStableLPToken {
    return new Contract(address, _abi, signerOrProvider) as IStableLPToken;
  }
}
