/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IWeightedPair, IWeightedPairInterface } from "../IWeightedPair";

const _abi = [
  {
    inputs: [],
    name: "getParameters",
    outputs: [
      {
        internalType: "uint32",
        name: "_tokenWeight0",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_tokenWeight1",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_swapFee",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_amp",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getReserves",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "reserve0",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "reserve1",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "vReserve0",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "vReserve1",
            type: "uint256",
          },
        ],
        internalType: "struct IWeightedPair.ReserveData",
        name: "reserveData",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWeightedPair__factory {
  static readonly abi = _abi;
  static createInterface(): IWeightedPairInterface {
    return new utils.Interface(_abi) as IWeightedPairInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWeightedPair {
    return new Contract(address, _abi, signerOrProvider) as IWeightedPair;
  }
}
